sonata_seo:
    encoding:         UTF-8
    page:
        title:            Hopenergie
        default:          sonata.seo.page.default
        metas:
            name:
                keywords:             Hopenergie
                description:          Comparateur électricité
                robots:               index, follow
                viewport:             width=device-width, initial-scale=1, shrink-to-fit=no
                author:               Hopenergie

            property:
                # Facebook application settings
                #'fb:app_id':          XXXXXX
                #'fb:admins':          admin1, admin2

                # Open Graph information
                # see http://developers.facebook.com/docs/opengraphprotocol/#types or http://ogp.me/
                'og:site_name':       Hopenergie
                'og:description':     Un plateforme de compatateur d'électricité

            http-equiv:
                'Content-Type':         text/html; charset=utf-8
                'X-Ua-Compatible':      IE=edge,chrome=1

            charset:
                UTF-8:    ''

        head:
            'xmlns':              http://www.w3.org/1999/xhtml
            'xmlns:og':           http://opengraphprotocol.org/schema/
            #'xmlns:fb':           "http://www.facebook.com/2008/fbml"
            'lang':               fr

    sitemap:
        doctrine_orm:
            # media
            # - { types: [image], connection: doctrine.dbal.default_connection, route: sonata_media_view,       parameters: {id: null},                               query: "SELECT id, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM media__media WHERE enabled = true" }
            # page - works only for one site, please adapt the code if required
            - {                 connection: doctrine.dbal.default_connection, route: page_slug,               parameters: {path: null},                             query: "SELECT url as path, updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority FROM page__snapshot WHERE route_name = 'page_slug' AND enabled = 1 AND url NOT LIKE '%%guides-old%%' AND (publication_date_start IS NULL OR publication_date_start <= NOW()) AND (publication_date_end IS NULL OR publication_date_end >= NOW())" }
            # Blog
            - {                 connection: doctrine.dbal.default_connection, route: hopenergie_blogview,     parameters: {identifier: null,category: null, pageType: null},        query: "SELECT b.identifier as identifier, b.updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority, REPLACE(c.name, ' ', '_') as category, case when page_type = 'guide' THEN 'guides'  ELSE 'actu-energie' END as pageType FROM blog b left join category c on c.category_type = 'blog' AND c.id = b.category_id WHERE  c.name IS NOT NULL AND b.body IS NOT NULL AND b.is_active = 1 AND (b.created_at IS NULL OR b.created_at <= NOW()) AND (b.updated_at IS NULL OR b.updated_at <= NOW())" }
            # Guide
            - {                 connection: doctrine.dbal.default_connection, route: hopenergie_blogview,     parameters: {identifier: null,category: null, pageType: null},        query: "SELECT b.identifier as category, b.updated_at as lastmod, 'weekly' as changefreq, '0.5' as priority, REPLACE(c.name, ' ', '_') as pageType FROM blog b left join category c on c.category_type = 'guide' AND c.id = b.category_id WHERE c.name IS NOT NULL AND b.body IS NOT NULL AND b.is_active = 1 AND (b.created_at IS NULL OR b.created_at <= NOW()) AND (b.updated_at IS NULL OR b.updated_at <= NOW())" }
            # Blog
            - {                 connection: doctrine.dbal.default_connection, route: hopenergie_bloglist_category,     parameters: {category: null,pageType: null},        query: "SELECT now() as lastmod, 'weekly' as changefreq, '0.5' as priority, REPLACE(name, ' ', '_') as category, case when category_type = 'guide' THEN 'guides'  ELSE 'actu-energie' END as pageType FROM category b WHERE b.name IS NOT NULL AND b.category_type = 'blog'" }
            # Guide
            - {                 connection: doctrine.dbal.default_connection, route: hopenergie_bloglist_category,     parameters: {category: null,pageType: null},        query: "SELECT now() as lastmod, 'weekly' as changefreq, '0.5' as priority, REPLACE(name, ' ', '_') as pageType FROM category b WHERE b.name IS NOT NULL AND b.category_type = 'guide'" }
