sonata_admin:
    templates:
        user_block: '/Sonata/user_block.html.twig'
       
    title: 'Sonata Admin'
    security:
        role_admin: ROLE_USER
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: center }
        groups:
            Group1:
                label: 'Group1'
                items: 
                    # - admin.basic-form
                    - admin.user
                    - admin.product
                # item:
                #     label: 'BasicForm'
                #     route: admin.basic-form
                # item:
                #     label: 'user'
                #     route: admin.user
                    
    options:
        html5_validate:  true     # enable or disable html5 form validation
        confirm_exit:    true     # enable or disable a confirmation before navigating away
        js_debug:        false    # enable or disable to show javascript debug messages
        use_select2:     true     # enable or disable usage of the Select2 jQuery library
        use_icheck:      true     # enable or disable usage of the iCheck library
        use_bootlint:    false    # enable or disable usage of Bootlint
        use_stickyforms: true     # enable or disable the floating buttons
        form_type:       standard # can also be 'horizontal'
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
