sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: right }
        groups:
            Group1:
                label: 'Group1'
                items:
                    route: admin.basic-form
                    

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
